ecommerce/Admin/urls.py
from django.urls import path
from . import views
from .views import toggle_user_status
from .views import toggle_category_status

urlpatterns = [
    path('login/',views.Admin_login,name="admin_login"),
    path('dashboard/',views.Dashboard,name="dashboard"),
    path('product_list/',views.Product_list,name="product_list"),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('add_product/',views.Add_Product,name="add_product"),
    path('category_list/',views.Category_list,name="category_list"),
    path('edit-category/', views.edit_category, name='edit_category'),
    path('all_customer/',views.All_customer,name="all_customer"),
    path('user/toggle_status/<int:user_id>/', toggle_user_status, name='toggle_user_status'),
    path('toggle-category-status/', toggle_category_status, name='toggle_category_status'),
    path('toggle-status/<int:product_id>/', views.toggle_product_status, name='toggle_product_status'),
    path('order_list/',views.Order_list,name="order_list"),
    path('admin/confirm-return/', views.confirm_return, name='confirm_return'),
    path('coupon/',views.coupon,name="coupon"),
    path('coupon/delete/<int:coupon_id>/', views.delete_coupon, name='delete_coupon'),
    path('sales_report/',views.sales_report,name="sales_report"),
    path('export_sales_report_pdf/', views.export_sales_report_pdf, name='export_sales_report_pdf'),
    path('export_sales_report_excel/', views.export_sales_report_excel, name='export_sales_report_excel'),  # Add this line
    path('offer/', views.offer, name='offer'),
    path('offer/add_category/', views.add_category_offer, name='add_category_offer'),
    path('offers/delete/<int:offer_id>/', views.delete_category_offer, name='delete_category_offer'),
    path('add-product-offer/', views.add_product_offer, name='add_product_offer'),
    path('delete-product-offer/<int:pk>/', views.delete_product_offer, name='delete_product_offer'),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from store.views import custom_404, custom_500

handler404 = 'store.views.custom_404'
handler500 = 'store.views.custom_500'
urlpatterns = [
    path('adminn/', admin.site.urls),
    path('',include('store.urls')),
    path('Admin/',include('Admin.urls')),
    path('accounts/', include('allauth.urls')),
    
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve static files in local development with DEBUG = False
if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone



# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"
        
        
        
class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
        
        
        

class Add_product(models.Model):
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    )

    title = models.CharField(max_length=200)
    description = models.TextField()
    image1 = models.ImageField(upload_to='admin_img/')
    image2 = models.ImageField(upload_to='admin_img/', blank=True, null=True)
    image3 = models.ImageField(upload_to='admin_img/', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE,null=True)
    # status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True, blank=True) 
    status = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True)  # Automatically updates on save

    def __str__(self):
        return self.title
    
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Cart {self.id} for {self.user}"

    @property
    def total_price(self):
        return sum(item.total_price for item in self.cartitem_set.all())

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Add_product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.product.title} ({self.quantity})"

    @property
    def total_price(self):
        return self.quantity * self.price



class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    street_address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postcode = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.street_address}, {self.city}"

    class Meta:
        verbose_name_plural = "Addresses"
        

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.user.username
    
class Order(models.Model):
    # Choices for payment method and status
    PAYMENT_METHOD_CHOICES = (
        ('cash on delivery', 'Cash on Delivery'),
        ('razorpay', 'Razorpay'),
        ('paypal', 'PayPal'),
    )

    PAYMENT_STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.ForeignKey('Address', on_delete=models.SET_NULL, null=True, blank=True)  # Change this line
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  # Add discount field
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, null=True)
    payment_status = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default='pending')
    payment_id = models.CharField(max_length=100, blank=True, null=True)  # Store payment ID from Razorpay/PayPal
    razorpay_order_id = models.CharField(max_length=100, null=True, blank=True)
    delivery_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"


    
    
    
class OrderItem(models.Model):
    STATUS_CHOICES = (
        ('purchased', 'Purchased'),
        ('returned', 'Returned'),
    )

    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Add_product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='purchased')

    def __str__(self):
        return f"{self.product.title} - {self.quantity} pcs"

    @property
    def total(self):
        return self.quantity * self.price

    
    
    

class OrderStatus(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('shipped', 'Shipped'),
        ('delivered', 'Delivered'),
        ('cancelled', 'Cancelled'),
        ('returned', 'Returned'),
    )

    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order {self.order.id} - {self.get_status_display()}"
    
    
class Size(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=50)
    color_code = models.CharField(max_length=7)  # HEX code

    def __str__(self):
        return self.name

class ProductVariant(models.Model):
    product = models.ForeignKey(Add_product, related_name='variants', on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.SET_NULL, null=True, blank=True)
    color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.product.title} - {self.size} - {self.color}"
    
    
class WishlistItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Add_product, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} - {self.product.name}'
    

class Coupon(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    ]

    name = models.CharField(max_length=100)
    code = models.CharField(max_length=50, unique=True)
    minimum_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_percentage = models.PositiveIntegerField()
    expiry_date = models.DateField()
    status = models.CharField(max_length=8, choices=STATUS_CHOICES, default='inactive')

    def __str__(self):
        return f"{self.name} - {self.code}"


class Wallet(models.Model):
    """
    Wallet model to store user's current balance.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Each user has one wallet
    balance = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)  # Wallet balance

    def __str__(self):
        return f"Wallet of {self.user.username} - Balance: RS {self.balance}"

    def credit(self, amount):
        """
        Method to credit the wallet (increase balance).
        """
        self.balance += amount
        self.save()
        return self.balance

    def debit(self, amount):
        """
        Method to debit the wallet (decrease balance), ensuring enough balance is available.
        """
        if self.balance >= amount:
            self.balance -= amount
            self.save()
            return self.balance
        else:
            raise ValueError(f"Insufficient balance in {self.user.username}'s wallet to complete this transaction.")
        


class Transaction(models.Model):
    """
    A model to track all wallet transactions (credit and debit).
    """
    TRANSACTION_TYPES = [
        ('credit', 'Credit'),
        ('debit', 'Debit'),
    ]

    wallet = models.ForeignKey(Wallet, related_name='transactions', on_delete=models.CASCADE)  # Wallet relationship
    timestamp = models.DateTimeField(auto_now_add=True)  # Automatically track when the transaction occurred
    description = models.TextField()  # Description of the transaction
    transaction_type = models.CharField(max_length=6, choices=TRANSACTION_TYPES)  # Either 'credit' or 'debit'
    amount = models.DecimalField(max_digits=12, decimal_places=2)  # Transaction amount

    def __str__(self):
        return f"{self.transaction_type.capitalize()} - RS {self.amount} on {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}"
    
    
    
    
class Offer(models.Model):
    # Choices for the type of offer
    OFFER_TYPE_CHOICES = (
        ('product', 'Product'),
        ('category', 'Category'),
    )

    # Choices for the status of the offer
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        ('expired', 'Expired'),
    )

    name = models.CharField(max_length=200)  # Name of the offer
    description = models.TextField(blank=True)  # Detailed description of the offer
    discount_percentage = models.PositiveIntegerField()  # Discount in percentage

ecommerce/Admin/templates/admin_login.html
{% load static %}

<!DOCTYPE html>


<html lang="en" class="light-style layout-wide  customizer-hide" dir="ltr" data-theme="theme-default" data-assets-path="../../assets/" data-template="vertical-menu-template" data-style="light">

  
<!-- Mirrored from demos.themeselection.com/materio-bootstrap-html-admin-template/html/vertical-menu-template/auth-login-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 25 Jun 2024 05:51:08 GMT -->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Login Basic - Pages | Materio - Bootstrap Material Design Admin Template</title>

    
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 5" />
    <meta name="keywords" content="dashboard, material, material design, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5">
    <!-- Canonical SEO -->
    <link rel="canonical" href="https://themeselection.com/item/materio-bootstrap-html-admin-template/">
    
    
    <!-- ? PROD Only: Google Tag Manager (Default ThemeSelection: GTM-5DDHKGP, PixInvent: GTM-5J3LMKC) -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-XXXX');</script>
    <!-- End Google Tag Manager -->
    
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="https://demos.themeselection.com/materio-bootstrap-html-admin-template/assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&amp;ampdisplay=swap" rel="stylesheet">

    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'aassets/dashboard-assets/vendor/fonts/remixicon/remixicon.css' %}" />
    <link rel="stylesheet" href="{% static 'aassets/dashboard-assets/vendor/fonts/flag-icons.css' %}" />
    
    <!-- Menu waves for no-customizer fix -->
    <link rel="stylesheet" href="{% static 'aassets/dashboard-assets/vendor/libs/node-waves/node-waves.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'aassets/dashboard-assets/vendor/css/rtl/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'aassets/dashboard-assets/vendor/css/rtl/theme-default.css' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static 'aassets/dashboard-assets/css/demo.css' %}" />
    
    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'aassets/dashboard-assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />
    <link rel="stylesheet" href="{% static 'aassets/dashboard-assets/vendor/libs/typeahead-js/typeahead.css' %}" /> 
    <!-- Vendor -->
<link rel="stylesheet" href="{% static 'aassets/dashboard-assets/vendor/libs/%40form-validation/form-validation.css' %}" />

    <!-- Page CSS -->
    <!-- Page -->
<link rel="stylesheet" href="{% static 'aassets/dashboard-assets/vendor/css/pages/page-auth.css' %}">

    <!-- Helpers -->
    <script src="{% static 'aassets/dashboard-assets/vendor/js/helpers.js' %}"></script>
    <script src="{% static 'aassets/dashboard-assets/js/config.js' %}"></script>
    
</head>

<body>

  
  <!-- ?PROD Only: Google Tag Manager (noscript) (Default ThemeSelection: GTM-5DDHKGP, PixInvent: GTM-5J3LMKC) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXX"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  
  <!-- Content -->

<div class="position-relative">
  <div class="authentication-wrapper authentication-basic container-p-y">
    <div class="authentication-inner py-6 mx-4">

      <!-- Login -->
      <div class="card p-7">
        <!-- Logo -->
        <div class="app-brand justify-content-center mt-5">
          <a href="index.html" class="app-brand-link gap-3"> 
            <span class="app-brand-logo demo">
<span style="color:#9055FD;">
    <img  src="{% static 'assets/images/venet/icononly.jpg' %}" alt="Venet Logo" width="80" height="90">
 
</span>
</span>
            <span class="app-brand-text demo text-heading fw-semibold">VENET</span>
          </a>
        </div>
        <!-- /Logo -->

        <div class="card-body mt-1">
          <h4 class="mb-1">Welcome to VENET! 👋🏻</h4>
          <p class="mb-5">Please sign-in to your account and start the adventure</p>

          <form id="formAuthentication" class="mb-5" action="" method="POST">
            {% csrf_token %}
            <div class="form-floating form-floating-outline mb-5">
              <input type="text" class="form-control" id="email" name="email-username" placeholder="Enter your email or username" autofocus>
              <label for="email">Email or Username</label>
            </div>
            <div class="mb-5">
              <div class="form-password-toggle">
                <div class="input-group input-group-merge">
                  <div class="form-floating form-floating-outline">
                    <input type="password" id="password" class="form-control" name="password" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" aria-describedby="password" />
                    <label for="password">Password</label>
                  </div>
                  <span class="input-group-text cursor-pointer"><i class="ri-eye-off-line ri-20px"></i></span>
                </div>
              </div>
            </div>
            <div class="message-boxx">
              {% if messages %} 
                  {% for message in messages %}
                      <p>{{message}}</p>
                  {% endfor %}
              {% endif %}
            </div>
            <div class="mb-5 pb-2 d-flex justify-content-between pt-2 align-items-center">
              <a href="{% url 'password_reset' %}">Forgot Password?</a>
            </div>
            <div class="mb-5">
              <button class="btn btn-primary d-grid w-100" type="submit">login</button>
            </div>
          </form>

          <p class="text-center mb-5">
            <span>New on our platform?</span>
            <a href="auth-register-basic.html">
              <span>Create an account</span>
            </a>
          </p>

          <div class="divider my-5">
            <div class="divider-text">or</div>
          </div>

          <div class="d-flex justify-content-center gap-2">
            <a href="javascript:;" class="btn btn-icon btn-lg rounded-pill btn-text-facebook">
              <i class="tf-icons ri-facebook-fill ri-24px"></i>
            </a>

            <a href="javascript:;" class="btn btn-icon btn-lg rounded-pill btn-text-twitter">
              <i class="tf-icons ri-twitter-fill ri-24px"></i>
            </a>

            <a href="javascript:;" class="btn btn-icon btn-lg rounded-pill btn-text-github">
              <i class="tf-icons ri-github-fill ri-24px"></i>
            </a>

            <a href="javascript:;" class="btn btn-icon btn-lg rounded-pill btn-text-google-plus">
              <i class="tf-icons ri-google-fill ri-24px"></i>
            </a>
          </div>
        </div>
      </div>
      <!-- /Login -->
      <img src="{% static 'aassets/dashboard-assets/img/illustrations/tree-3.png' %}" alt="auth-tree" class="authentication-image-object-left d-none d-lg-block">
      <img src="{% static 'aassets/dashboard-assets/img/illustrations/auth-basic-mask-light.png' %}" class="authentication-image d-none d-lg-block scaleX-n1-rtl" height="172" alt="triangle-bg" data-app-light-img="illustrations/auth-basic-mask-light.png" data-app-dark-img="illustrations/auth-basic-mask-dark.html">
      <img src="{% static 'aassets/dashboard-assets/img/illustrations/tree.png' %}" alt="auth-tree" class="authentication-image-object-right d-none d-lg-block">
    </div>
  </div>
</div>

<!-- / Content -->

  
 
  

  <div class="container">
    {% block content %}
    {% endblock content %}
</div>
  

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  
  <script src="{% static 'aassets/dashboard-assets/vendor/libs/popper/popper.js' %}"></script>
  <script src="{% static 'aassets/dashboard-assets/vendor/js/bootstrap.js' %}"></script>
  <script src="{% static 'aassets/dashboard-assets/vendor/libs/node-waves/node-waves.js' %}"></script>
  <script src="{% static 'aassets/dashboard-assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
  <script src="{% static 'aassets/dashboard-assets/vendor/libs/hammer/hammer.js' %}"></script>
  <script src="{% static 'aassets/dashboard-assets/vendor/libs/i18n/i18n.js' %}"></script>
  <script src="{% static 'aassets/dashboard-assets/vendor/libs/typeahead-js/typeahead.js' %}"></script>
  <script src="{% static 'aassets/dashboard-assets/vendor/js/menu.js' %}"></script>
  
  <!-- endbuild -->

  <!-- Vendors JS -->
  <script src="{% static 'aassets/dashboard-assets/vendor/libs/%40form-validation/popular.js' %}"></script>
<script src="{% static 'aassets/dashboard-assets/vendor/libs/%40form-validation/bootstrap5.js' %}"></script>
<script src="{% static 'aassets/dashboard-assets/vendor/libs/%40form-validation/auto-focus.js' %}"></script>

  <!-- Main JS -->
  <script src="{% static 'aassets/dashboard-assets/js/main.js' %}"></script>
  

  <!-- Page JS -->
  <script src="{% static 'aassets/dashboard-assets/js/pages-auth.js' %}"></script>
  
</body>


<!-- Mirrored from demos.themeselection.com/materio-bootstrap-html-admin-template/html/vertical-menu-template/auth-login-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 25 Jun 2024 05:51:08 GMT -->
</html>

<!-- beautify ignore:end -->

ecommerce/Admin/templates/sales_report_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sales Report PDF</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        h2 {
            text-align: center;
        }
    </style>
</head>
<body>
    <h2>Sales Report</h2>
    <p>Total Orders: {{ total_orders }}</p>
    <p>Total Sales Amount: RS: {{ total_sales_amount|floatformat:2 }}</p>

    <table>
        <thead>
            <tr>
                <th>Order Id</th>
                <th>Customer Name</th>
                <th>Order Date</th>
                <th>Total Amount</th>
                <th>Payment Method</th>
                <th>Payment Status</th>
                <th>Order Status</th>
            </tr>
        </thead>
        <tbody>
            {% for order in order_details %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.user.username }}</td>
                <td>{{ order.created_at|date:"d/m/Y" }}</td>
                <td>RS: {{ order.total_amount|floatformat:2 }}</td>
                <td>{{ order.get_payment_method_display }}</td>
                <td>{{ order.payment_status }}</td>
                <td>{{ order.orderstatus.get_status_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>